version: 2

sources:
  - name: public  
    description: "Raw USGS Earthquake Data"
    database: EARTHQUAKE_USGS  
    schema: public  
    tables:
      - name: raw_earthquake_history  
      
  - name: stg_usgs  
    description: "Transformed USGS Earthquake Data"
    database: EARTHQUAKE_USGS  
    schema: STG_EARTHQUAKE_DATA  
    tables:
      - name: STG_EARTHQUAKE_HISTORY  
